In [1]:
import numpy as np

# Zadanie 1
## Wylosuj wektor x 30 liczb z rozkładu jednostajnego z przedziału [−4, 4]. Następnie wyznacz:

In [2]:
np.random.seed(123)
x = np.random.uniform(low=-4, high=4, size=30)
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ,
        1.07520767,  2.79545435,  1.7956426 ,  0.88818809,  1.77954706,
       -1.41632869, -1.10569076, -2.17389415, -1.65028763,  1.04780899])

In [7]:
# A) wszystkie wartości ze zbioru [−2, −1] i [1, 2]
x[((x>-2) & (x<-1)) | ((x>1) & (x<2))]

array([ 1.57175348, -1.71088532,  1.75575176,  1.47863791, -1.25457587,
        1.83239766,  1.90396325,  1.07520767,  1.7956426 ,  1.77954706,
       -1.41632869, -1.10569076, -1.65028763,  1.04780899])

In [15]:
# B) liczbę wszystkich wartości nieujemnych
x[x>=0].size # raczej tak nie
np.sum(x >= 0)

15

In [16]:
# C) średnią arytmetyczną wartości bezwzględnych (modułów) elementów
np.mean(np.abs(x))
# w np.average mozna podac wagi

1.5260572308400788

In [13]:
# D) najmniejszą i największą wartość
print(np.max(x))
print(np.min(x))

3.846113587076924
-3.522576827123453


In [25]:
# E) wartość najbliższą i najdalszą od 0 (zachowując jej znak)
odleglosci = np.abs(x-0)

x[np.argmin(odleglosci)], x[np.argmax(odleglosci)]

(-0.15254478812511252, 3.846113587076924)

In [26]:
# F) wartość najbliższą i najdalszą od 2 (zachowując jej znak)
odleglosci = np.abs(x-2)

x[np.argmin(odleglosci)], x[np.argmax(odleglosci)]

(1.9039632458562856, -3.522576827123453)

In [28]:
# G) część ułamkową wszystkich elementów
#• -1.23 -> -0.23
#• 2.23 -> 0.23
#• 3.99 -> 0.99
#• -4.99 -> -0.99

np.modf(x)[0]

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

In [29]:
# H) interpolację liniową tego wektora na przedział [-1, 1].....
def interpolate(x):
    x_min = np.min(x)
    x_max = np.max(x)
    y_min = -1
    y_max = 1
    
    return ((x-x_min)/(x_max-x_min))*(y_max-y_min) + y_min

interpolate(x)

array([ 0.38269625, -0.50827314, -0.63700783,  0.06751533,  0.43263682,
       -0.21086968,  1.        ,  0.35742295, -0.08531046, -0.2781575 ,
       -0.38442224,  0.45343994, -0.17728806, -1.        , -0.26528848,
        0.47286418, -0.73332828, -0.74861452,  0.02460209,  0.02520185,
        0.24792446,  0.71483149,  0.44346393,  0.19716386,  0.4390953 ,
       -0.42832498, -0.34401205, -0.63394237, -0.49182579,  0.24048795])

In [35]:
# I) średnią wartość kwadratów liczb większych od 3 lub mniejszych od −2

np.mean(x[(x > 3) | (x < -2)]**2)

8.315859553206058

In [3]:
# J) utwórz wektor napisów y o długości takiej samej, jaką ma x, dla którego y i przyjmuje wartość
#'nieujemna', jeśli x i jest nieujemne oraz 'ujemna' w przeciwnym wypadku

y = np.where(x > 0, 'nieujemna', 'ujemna')
y

array(['nieujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna',
       'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna',
       'ujemna', 'ujemna', 'nieujemna'], dtype='<U9')

In [6]:
# K) jego średnią (bez używania funkcji mean())
np.sum(x)/np.size(x)

-0.01352281479601792

In [11]:
# L) minimum i maksimum, ale nie używając funkcji min() i max() (rozwiązanie nie musi być optymalne)
sorted = np.sort(x)
max = sorted[0]
min = sorted[-1]
max, min

(-3.522576827123453, 3.846113587076924)

In [12]:
# M) utwórz wektor liczbowy y o długości takiej samej, jaką ma x......
np.floor(x)+0.5

array([ 1.5, -1.5, -2.5,  0.5,  1.5, -0.5,  3.5,  1.5, -0.5, -0.5, -1.5,
        1.5, -0.5, -3.5, -0.5,  1.5, -2.5, -2.5,  0.5,  0.5,  1.5,  2.5,
        1.5,  0.5,  1.5, -1.5, -1.5, -2.5, -1.5,  1.5])

# Zadanie 2
## Dla dwóch wektorów równej długości x i y oblicz ich korelację ze wzoru:

In [21]:
# A)
x=np.array([1,2,3,4,5,6,7,8,9,10])
y=np.array([10,9,8,7,6,5,4,3,2,1])

x_mean = np.mean(x)
y_mean = np.mean(y)

def correlation1():
    licznik = sum((x-x_mean)*(y-y_mean))
    n = x.size

    mianownik = np.sqrt(sum((x-x_mean)**2)) * np.sqrt(sum((y-y_mean)**2))

    return licznik/mianownik

correlation1()

-1.0

# Zadanie 3
## Napisz funkcję, która standaryzuje wartości w podanym wektorze numerycznym, tj. przeskalowuje elementy w taki sposób, że ich średnia jest równa 0, a odchylenie standardowe 1.

In [27]:
x=np.array([1,2,3,4,5,6,7,8,9,10])

def skalowanie(x):
    return (x - np.mean(x))/np.std(x)

x_standaryzowany = skalowanie(x)

In [28]:
np.mean(x_standaryzowany)

-6.661338147750939e-17

In [29]:
np.std(x_standaryzowany)

1.0

# Zadanie 4
## Oblicz iloczyn skalarny dwóch wektorów (suma iloczynów ich współrzędnych)

In [30]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
y=np.array([10,9,8,7,6,5,4,3,2,1])

iloczyn = x.dot(y)
iloczyn

220

# Zadanie 5
## Oblicz trzy miary błędu pomiędzy wektorami:

In [33]:
# A) Oblicz root-mean-squared-error pomiędzy dwoma wektorami:
x=np.array([1,2,3,4,5,6,7,8,9,10])
y=np.array([10,9,8,7,6,5,4,3,2,1])
def rmse(x,y):
    return np.sqrt(np.mean((x-y)**2))

In [34]:
# B) 
def mae(x,y):
    return np.mean(np.abs(x-y))

In [35]:
# C)
def medAE(x,y):
    return np.median(np.abs(x-y))

In [36]:
rmse(x,y), mae(x,y), medAE(x,y)

(5.744562646538029, 5.0, 5.0)

# Zadanie 7
## Oblicz miarę błędu o nazwie cross-entropy loss

In [37]:
y = np.array([1,1,0,0,1,0])
y_hat = np.array([0.9,0.8,0.2,0.3,0.6,0.4])

In [38]:
-np.mean(y*np.log10(y_hat) + (1-y)*np.log10(1-y_hat))

0.13969616263254062

# Zadanie 8
## Dla danego wektora liczbowego zawierającego braki danych (NaN) uzupełnij je średnią wartością z pozostałych, poprawnych wartości.

In [41]:
nanwek = np.array([1, np.NaN, 3, np.NaN])

In [52]:

avg = np.mean(nanwek[np.isnan(nanwek) == False])
avg

2.0

In [54]:
nanwek[np.isnan(nanwek)] = avg


In [55]:
nanwek

array([1., 2., 3., 2.])